### ISSUE TITLE
Component Size

### ISSUE THREAD

**Issue by JeffersonSchuler** [SeanSobey/ChartjsNodeCanvas#33]
I use your component in an AWS Lambda and noticed that version 3.x has gone from 300K to 4.32MB in size.  Due to the size increate our deployment now exceeds the unzipped size allowed by AWS.  I was just wondering what the changes were to 3.x and if sticking with version 2.4.2 would be okay.

Thanks.

**Comment by SeanSobey** [comment]
Hi, thanks for reporting this.

This was a result of adding some testing and reporting tooling but forgetting to update the `.npmignore` to exclute test data and generated reports. I have pushed up a fix and version `3.0.2` is down to 200.0 kB. I also want to look into a CI step to check package size growth but for now, just the update is available.

It is also worth mentioning that the upstream dependency `canvas` binaries can be quite large as well, I might need to monitor those as well.

**Comment by JeffersonSchuler** [comment]
Thanks for the quick response.  Unfortunately version 3.0.2 is still showing close to 4MB in size.  coverage-2116-1581926541325-0.json is 3.9MB.

**Comment by SeanSobey** [comment]
Ahh missed the coverage folder. Updated to `3.0.3` with the fix.

**Comment by JeffersonSchuler** [comment]
Thanks, I was able to deploy again.
